export type Texts = {
  app: {
    description: string
    displayname: string
    warning_remove_2fa_device: string
    warning_remove_2step_device: string
    warning_remove_the_last_2fa_device: string
    warning_remove_the_last_2step_device: string
  }
  authenticator: {
    "2fa_authenticator_desc": string
    "2fa_desc": string
    "2fa_login_flow": string
    "2fa_note_scan_qr_code": string
    "2fa_setup_finish_desc": string
    "2fa_with_authenticator": string
    app_version: string
    approve_sign_in: string
    authenticator_desc: string
    enforce_2fa_authenticator_desc: string
    install_authenticator: string
    install_authenticator_desc: string
    login_desc: string
    login_flow: string
    login_page_desc: string
    login_request_resend: string
    login_request_resend_button: string
    management_empty_text: string
    mobile_wait_too_long_info: string
    model: string
    note_scan_qr_code: string
    os_version: string
    private_ip_error_msg_admin: string
    private_ip_error_msg_admin_with_params: string
    private_ip_error_msg_user: string
    receive_sign_in_request: string
    recv_sign_in_requests: string
    register_unavailable_title: string
    request_denied: string
    request_denied_desc: string
    request_sent_desc: string
    request_sent_num_desc: string
    request_timeout: string
    request_timeout_desc: string
    scan_qr_code: string
    setup_authenticator: string
    setup_authenticator_desc: string
    sign_in_method: string
    sign_in_with_authenticator: string
    tap_to_continue: string
    try_again: string
  }
  common: {
    "2fa_off": string
    "2fa_on": string
    "2fa_package_broken_msg": string
    add_time: string
    continue: string
    last_used_time: string
    package_broken_msg: string
    passwordless_off: string
    passwordless_on: string
    passwordless_signin: string
    setup_success: string
    turn_off: string
  }
  error: {
    invalid_device_name: string
    invalid_domain: string
    invalid_domain_user: string
    other_ways_desc: string
    register_again: string
    something_wrong: string
  }
  fido: {
    complete_login: string
    follow_steps: string
    hardware_security_key: string
    keyname_collision: string
    login_page_desc: string
    mac_touch_id_setup_desc: string
    management_empty_text: string
    method_touch_id: string
    method_usb_key: string
    method_windows_hello: string
    name_your_key: string
    platform_key_not_setup_desc: string
    reg_wizard_usb_key_title: string
    register_duplicate_key: string
    security_key_registered: string
    security_key_registered_desc: string
    securiy_key_registered: string // note: typo in key preserved
    select_type: string
    set_up_ddns: string
    set_up_ddns_desc: string
    touch_id_2fa_desc: string
    touch_id_desc: string
    touch_id_disabled: string
    touch_id_login_desc: string
    touch_id_login_desc_with_otp: string
    touch_id_not_set_up_desc: string
    touch_id_not_set_up_title: string
    touch_id_reg: string
    touch_id_setup_desc: string
    type_touch_id: string
    type_usb_key: string
    type_windows_hello: string
    usb_key_2fa_desc: string
    usb_key_desc: string
    usb_key_login_desc: string
    usb_key_login_desc_with_otp: string
    usb_key_name: string
    usb_key_name_desc: string
    usb_key_reg: string
    usb_key_reg_desc: string
    use_registered_hostname_desc: string
    use_registered_hostname_desc_with_params: string
    use_valid_domain_title: string
    verifying: string
    windows_hello_2fa_desc: string
    windows_hello_desc: string
    windows_hello_disabled: string
    windows_hello_login_desc: string
    windows_hello_login_desc_with_otp: string
    windows_hello_not_set_up_desc: string
    windows_hello_not_set_up_title: string
    windows_hello_reg: string
    windows_hello_setup_desc: string
  }
  inherit: {
    "2fa_desc": string
    "2fa_no": string
    "2fa_note": string
    "2fa_title": string
    "2fa_yes": string
    inherit_to_2fa_desc: string
    inherit_to_2fa_title: string
    inherit_to_passwordless_desc: string
    inherit_to_passwordless_title: string
    passwordless_desc: string
    passwordless_no: string
    passwordless_note: string
    passwordless_title: string
    passwordless_yes: string
  }
  management: {
    "2fa_desc": string
    "2fa_settings_activated_time": string
    "2fa_settings_general_desc": string
    alert_disable_2fa: string
    alert_disable_2fa_title: string
    alert_disable_passwordless: string
    alert_disable_passwordless_title: string
    chagne_mobile_device_title: string // note: typo kept as in JSON
    change_mobile_device_desc: string
    change_mobile_device_title: string
    device_name: string
    edit_device_name: string
    enforce_2fa_by_admin: string
    enforce_2fa_remove_last_signin: string
    passwordless_desc: string
    passwordless_settings_activated_time: string
    passwordless_settings_general_desc: string
    remove_a_2fa_signin: string
    remove_a_passwordless_signin: string
    remove_last_2fa_signin: string
    remove_last_2fa_signin_and_otp_disabled: string
    remove_last_passwordless_signin: string
    reset_current_mobile_device: string
    trusted_device_desc: string
    unavailable_sa_desc_admin: string
    unavailable_sa_desc_user: string
  }
  otp: {
    "2fa_summary_desc": string
    "2fa_summary_note": string
    backup_email_admin_tip: string
    backup_email_desc: string
    backup_email_note_desc: string
    backup_email_user_tip: string
    download_qrcode_note: string
    email_service_provider: string
    management_empty_text: string
    no_service_provider_or_backup_email: string
    note_desc: string
    otp_backup_mail_settings_desc: string
    otp_wizard_backup_method_welcome_desc: string
    otp_wizard_backup_method_welcome_note: string
    otp_wizard_welcome_desc: string
    otp_wizard_welcome_note: string
    reomte_admin_email_update_info: string
    reomte_user_email_update_info: string
    skip_backup_email_warning_msg: string
    skip_warning_msg: string
    wizard_mail_step_no_sender_desc: string
  }
  personal_setting: {
    "2fa_desc": string
    first_signin_step: string
    first_signin_step_desc: string
    no_sa_signin_method_desc: string
    passwordless_signin_desc: string
    second_signin_step: string
    signin_method_desc: string
  }
  wizard: {
    "2fa_desc": string
    "2fa_has_been_turned_on": string
    "2fa_title": string
    add_alternative_signin_method: string
    add_new_signin_methods: string
    confirm_rollback: string
    confirm_rollback_title: string
    enforce_2fa_headline: string
    enforce_2fa_welcome_desc1: string
    enforce_2fa_welcome_desc2: string
    hardware_security_key_desc: string
    leave_desc: string
    passwordless_desc: string
    passwordless_title: string
    set_backup_2fa_content: string
    set_backup_2fa_desc: string
  }
}